print 'inserting into dbo.Timezones'

insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Dateline Standard Time', -720, '(UTC-12:00) International Date Line West')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('UTC-11', -660, '(UTC-11:00) Coordinated Universal Time-11')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Aleutian Standard Time', -600, '(UTC-10:00) Aleutian Islands')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Hawaiian Standard Time', -600, '(UTC-10:00) Hawaii')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Marquesas Standard Time', -570, '(UTC-09:30) Marquesas Islands')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Alaskan Standard Time', -540, '(UTC-09:00) Alaska')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('UTC-09', -540, '(UTC-09:00) Coordinated Universal Time-09')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Pacific Standard Time (Mexico)', -480, '(UTC-08:00) Baja California')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('UTC-08', -480, '(UTC-08:00) Coordinated Universal Time-08')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Pacific Standard Time', -480, '(UTC-08:00) Pacific Time (US & Canada)')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('US Mountain Standard Time', -420, '(UTC-07:00) Arizona')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Mountain Standard Time (Mexico)', -420, '(UTC-07:00) Chihuahua, La Paz, Mazatlan')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Mountain Standard Time', -420, '(UTC-07:00) Mountain Time (US & Canada)')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Central America Standard Time', -360, '(UTC-06:00) Central America')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Central Standard Time', -360, '(UTC-06:00) Central Time (US & Canada)')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Easter Island Standard Time', -360, '(UTC-06:00) Easter Island')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Central Standard Time (Mexico)', -360, '(UTC-06:00) Guadalajara, Mexico City, Monterrey')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Canada Central Standard Time', -360, '(UTC-06:00) Saskatchewan')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('SA Pacific Standard Time', -300, '(UTC-05:00) Bogota, Lima, Quito, Rio Branco')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Eastern Standard Time (Mexico)', -300, '(UTC-05:00) Chetumal')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Eastern Standard Time', -300, '(UTC-05:00) Eastern Time (US & Canada)')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Haiti Standard Time', -300, '(UTC-05:00) Haiti')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Cuba Standard Time', -300, '(UTC-05:00) Havana')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('US Eastern Standard Time', -300, '(UTC-05:00) Indiana (East)')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Paraguay Standard Time', -240, '(UTC-04:00) Asuncion')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Atlantic Standard Time', -240, '(UTC-04:00) Atlantic Time (Canada)')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Venezuela Standard Time', -240, '(UTC-04:00) Caracas')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Central Brazilian Standard Time', -240, '(UTC-04:00) Cuiaba')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('SA Western Standard Time', -240, '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Pacific SA Standard Time', -240, '(UTC-04:00) Santiago')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Turks And Caicos Standard Time', -240, '(UTC-04:00) Turks and Caicos')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Newfoundland Standard Time', -210, '(UTC-03:30) Newfoundland')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Tocantins Standard Time', -180, '(UTC-03:00) Araguaina')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('E. South America Standard Time', -180, '(UTC-03:00) Brasilia')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('SA Eastern Standard Time', -180, '(UTC-03:00) Cayenne, Fortaleza')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Argentina Standard Time', -180, '(UTC-03:00) City of Buenos Aires')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Greenland Standard Time', -180, '(UTC-03:00) Greenland')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Montevideo Standard Time', -180, '(UTC-03:00) Montevideo')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Magallanes Standard Time', -180, '(UTC-03:00) Punta Arenas')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Saint Pierre Standard Time', -180, '(UTC-03:00) Saint Pierre and Miquelon')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Bahia Standard Time', -180, '(UTC-03:00) Salvador')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('UTC-02', -120, '(UTC-02:00) Coordinated Universal Time-02')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Mid-Atlantic Standard Time', -120, '(UTC-02:00) Mid-Atlantic - Old')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Azores Standard Time', -60, '(UTC-01:00) Azores')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Cape Verde Standard Time', -60, '(UTC-01:00) Cabo Verde Is.')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('UTC', 0, '(UTC) Coordinated Universal Time')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Morocco Standard Time', 0, '(UTC+00:00) Casablanca')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('GMT Standard Time', 0, '(UTC+00:00) Dublin, Edinburgh, Lisbon, London')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Greenwich Standard Time', 0, '(UTC+00:00) Monrovia, Reykjavik')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('W. Europe Standard Time', 60, '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Central Europe Standard Time', 60, '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Romance Standard Time', 60, '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Central European Standard Time', 60, '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('W. Central Africa Standard Time', 60, '(UTC+01:00) West Central Africa')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Namibia Standard Time', 60, '(UTC+01:00) Windhoek')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Jordan Standard Time', 120, '(UTC+02:00) Amman')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('GTB Standard Time', 120, '(UTC+02:00) Athens, Bucharest')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Middle East Standard Time', 120, '(UTC+02:00) Beirut')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Egypt Standard Time', 120, '(UTC+02:00) Cairo')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('E. Europe Standard Time', 120, '(UTC+02:00) Chisinau')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Syria Standard Time', 120, '(UTC+02:00) Damascus')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('West Bank Standard Time', 120, '(UTC+02:00) Gaza, Hebron')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('South Africa Standard Time', 120, '(UTC+02:00) Harare, Pretoria')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('FLE Standard Time', 120, '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Israel Standard Time', 120, '(UTC+02:00) Jerusalem')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Kaliningrad Standard Time', 120, '(UTC+02:00) Kaliningrad')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Sudan Standard Time', 120, '(UTC+02:00) Khartoum')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Libya Standard Time', 120, '(UTC+02:00) Tripoli')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Arabic Standard Time', 180, '(UTC+03:00) Baghdad')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Turkey Standard Time', 180, '(UTC+03:00) Istanbul')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Arab Standard Time', 180, '(UTC+03:00) Kuwait, Riyadh')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Belarus Standard Time', 180, '(UTC+03:00) Minsk')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Russian Standard Time', 180, '(UTC+03:00) Moscow, St. Petersburg, Volgograd')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('E. Africa Standard Time', 180, '(UTC+03:00) Nairobi')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Iran Standard Time', 210, '(UTC+03:30) Tehran')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Arabian Standard Time', 240, '(UTC+04:00) Abu Dhabi, Muscat')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Astrakhan Standard Time', 240, '(UTC+04:00) Astrakhan, Ulyanovsk')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Azerbaijan Standard Time', 240, '(UTC+04:00) Baku')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Russia Time Zone 3', 240, '(UTC+04:00) Izhevsk, Samara')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Mauritius Standard Time', 240, '(UTC+04:00) Port Louis')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Saratov Standard Time', 240, '(UTC+04:00) Saratov')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Georgian Standard Time', 240, '(UTC+04:00) Tbilisi')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Caucasus Standard Time', 240, '(UTC+04:00) Yerevan')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Afghanistan Standard Time', 270, '(UTC+04:30) Kabul')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('West Asia Standard Time', 300, '(UTC+05:00) Ashgabat, Tashkent')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Ekaterinburg Standard Time', 300, '(UTC+05:00) Ekaterinburg')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Pakistan Standard Time', 300, '(UTC+05:00) Islamabad, Karachi')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('India Standard Time', 330, '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Sri Lanka Standard Time', 330, '(UTC+05:30) Sri Jayawardenepura')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Nepal Standard Time', 345, '(UTC+05:45) Kathmandu')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Central Asia Standard Time', 360, '(UTC+06:00) Astana')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Bangladesh Standard Time', 360, '(UTC+06:00) Dhaka')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Omsk Standard Time', 360, '(UTC+06:00) Omsk')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Myanmar Standard Time', 390, '(UTC+06:30) Yangon (Rangoon)')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('SE Asia Standard Time', 420, '(UTC+07:00) Bangkok, Hanoi, Jakarta')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Altai Standard Time', 420, '(UTC+07:00) Barnaul, Gorno-Altaysk')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('W. Mongolia Standard Time', 420, '(UTC+07:00) Hovd')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('North Asia Standard Time', 420, '(UTC+07:00) Krasnoyarsk')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('N. Central Asia Standard Time', 420, '(UTC+07:00) Novosibirsk')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Tomsk Standard Time', 420, '(UTC+07:00) Tomsk')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('China Standard Time', 480, '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('North Asia East Standard Time', 480, '(UTC+08:00) Irkutsk')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Singapore Standard Time', 480, '(UTC+08:00) Kuala Lumpur, Singapore')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('W. Australia Standard Time', 480, '(UTC+08:00) Perth')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Taipei Standard Time', 480, '(UTC+08:00) Taipei')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Ulaanbaatar Standard Time', 480, '(UTC+08:00) Ulaanbaatar')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('North Korea Standard Time', 510, '(UTC+08:30) Pyongyang')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Aus Central W. Standard Time', 525, '(UTC+08:45) Eucla')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Transbaikal Standard Time', 540, '(UTC+09:00) Chita')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Tokyo Standard Time', 540, '(UTC+09:00) Osaka, Sapporo, Tokyo')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Korea Standard Time', 540, '(UTC+09:00) Seoul')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Yakutsk Standard Time', 540, '(UTC+09:00) Yakutsk')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Cen. Australia Standard Time', 570, '(UTC+09:30) Adelaide')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('AUS Central Standard Time', 570, '(UTC+09:30) Darwin')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('E. Australia Standard Time', 600, '(UTC+10:00) Brisbane')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('AUS Eastern Standard Time', 600, '(UTC+10:00) Canberra, Melbourne, Sydney')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('West Pacific Standard Time', 600, '(UTC+10:00) Guam, Port Moresby')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Tasmania Standard Time', 600, '(UTC+10:00) Hobart')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Vladivostok Standard Time', 600, '(UTC+10:00) Vladivostok')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Lord Howe Standard Time', 630, '(UTC+10:30) Lord Howe Island')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Bougainville Standard Time', 660, '(UTC+11:00) Bougainville Island')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Russia Time Zone 10', 660, '(UTC+11:00) Chokurdakh')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Magadan Standard Time', 660, '(UTC+11:00) Magadan')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Norfolk Standard Time', 660, '(UTC+11:00) Norfolk Island')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Sakhalin Standard Time', 660, '(UTC+11:00) Sakhalin')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Central Pacific Standard Time', 660, '(UTC+11:00) Solomon Is., New Caledonia')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Russia Time Zone 11', 720, '(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('New Zealand Standard Time', 720, '(UTC+12:00) Auckland, Wellington')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('UTC+12', 720, '(UTC+12:00) Coordinated Universal Time+12')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Fiji Standard Time', 720, '(UTC+12:00) Fiji')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Kamchatka Standard Time', 720, '(UTC+12:00) Petropavlovsk-Kamchatsky - Old')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Chatham Islands Standard Time', 765, '(UTC+12:45) Chatham Islands')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('UTC+13', 780, '(UTC+13:00) Coordinated Universal Time+13')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Tonga Standard Time', 780, '(UTC+13:00) Nuku''alofa')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Samoa Standard Time', 780, '(UTC+13:00) Samoa')
insert into dbo.Timezones (TimezoneId, BaseUtcOffsetInMinutes, DisplayName) values ('Line Islands Standard Time', 840, '(UTC+14:00) Kiritimati Island')

